name: lastOne
version: 1.0
main: lastOne.Main

commands:
  lastone:
    description: "lastOne"
    
  reset:
    description: "reset"
  
  create_party:
    description: "create party"
  join_party:
    description: "party join"
  party:
    description: "manage party"
  c:
    description: "nothing"